### ISSUE TITLE
Cant find resource files

### ISSUE THREAD

**Issue by Styx0x0** [hsheric0210/AntiDebug.NET#5]
Missing "AntiDebugLibNative_Win32", "AntiDebugLibNative_x64", Please provide necessary files to build project

**Comment by hsheric0210** [comment]
Fixed @ 0c5fccac35d395ea76e6d2f110781c29823f8b9f

(Or you can simply fix this erorr by building 'AntiDebugLibNative' project in both x64 and Win32 before building other projects or the entire solution)

**Comment by hsheric0210** [comment]
Note that in the build process, the native DLL (AntiDebugLibNative) is copied and embedded to AntiDebugLib _in encrypted form_. And you can scramble the encryption key entry point name by running the script 'ChangeMagics.ps1'
